### ISSUE TITLE
Gemfile lists active_support. Should be activesupport

### ISSUE THREAD

**Issue by simonvc** [chef/knife-vcloud#5]
I was able to install and use this plugin only after i replaced active_support with activesupport.

$ bundle install                                     
Fetching gem metadata from https://www.rubygems.org/.........                              
Fetching gem metadata from https://www.rubygems.org/..                                     
Resolving dependencies...                                                                  
Could not find gem 'active_support (>= 0) ruby' in the gems available on this machine.

**Comment by tas50** [comment]
This was fixed and the repo is deprecated
